apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: org2-peer2-tls-cert
  namespace: ${ORG2_NS}
spec:
  isCA: false
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - localhost
    - org2-peer2
    - org2-peer-gateway-svc
    - org2-peer2.${ORG2_NS}.svc.cluster.local
    - org2-peer2.${DOMAIN}
  ipAddresses:
    - 127.0.0.1
  secretName: org2-peer2-tls-cert
  issuerRef:
    name: org2-tls-cert-issuer